#!/usr/bin/env python3
"""Build candidate-specific blinded NATIONAL_CTX_V1 (selector-side resolution)."""
import argparse,csv,hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'output/research/csr/national_capital'
def canon(x):return json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':'))
def num(x):
 try:return float(x) if x not in ('',None) else None
 except:return None
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--ordinal',type=int,required=True);ap.add_argument('--packet-id');ap.add_argument('--as-of');ap.add_argument('--out',required=True);a=ap.parse_args();sys.path.insert(0,str(ROOT/'scripts'));import csr8_phase_c_annotation_seal as c4d
 cand=c4d.candidate_for_ordinal(a.ordinal);T=cand['T'];ocid=cand['opaque_case_id'];packet=c4d.c1.packet_id(ocid,T)
 if a.packet_id and a.packet_id!=packet:raise SystemExit('packet-id does not match candidate_for_ordinal')
 if a.as_of and a.as_of!=T:raise SystemExit('as-of does not match candidate_for_ordinal')
 salt=c4d.c1.load_salt();plan=json.loads(c4d.c1.PLAN_FILE.read_text());matches=[e for e in plan['entries'] if c4d.c1.opaque_case_id(salt,e['case_key'])==ocid and e['T']==T]
 if len(matches)!=1:raise SystemExit('candidate identity resolution is not unique')
 stock_code=matches[0]['case_key'].split('|')[1];h=list(csv.DictReader((OUT/'national_holdings_pit.csv').open()));all_rows=[r for r in h if r['stock_code']==stock_code]; periods={r['report_period'] for r in all_rows if r.get('available_date') not in ('','UNKNOWN') and r['available_date']<=T}; complete={p for p in periods if any(r['report_period']==p and r.get('table_complete')=='True' for r in all_rows)};ordered=sorted(complete,key=lambda p:max(r['available_date'] for r in all_rows if r['report_period']==p));latest_period=ordered[-1] if ordered else None;previous_period=ordered[-2] if len(ordered)>1 else None
 latest=[r for r in all_rows if r['report_period']==latest_period] if latest_period else [];previous=[r for r in all_rows if r['report_period']==previous_period] if previous_period else [];latest_by={r.get('actor_id'):r for r in latest if r.get('actor_id')};previous_by={r.get('actor_id'):r for r in previous if r.get('actor_id')};actors=sorted(set(latest_by)|set(previous_by));stock=[]
 for i,actor in enumerate(actors):
  cur=latest_by.get(actor);prev=previous_by.get(actor);state='UNKNOWN' if not latest_period else ('FIRST_DISCLOSED' if cur and not prev else 'NOT_DISCLOSED_IN_TOP10' if not cur and prev else 'UNKNOWN' if not cur else 'INCREASE' if num(cur.get('holding_ratio'))>num(prev.get('holding_ratio')) else 'DECREASE' if num(cur.get('holding_ratio'))<num(prev.get('holding_ratio')) else 'STABLE');base=cur or prev;stock.append({'context_record_id':f'S-{i:06d}','capital_layer':'STOCK','evidence_type':'NATIONAL_ACTOR_HOLDING_STATE','actor_id':actor,'state':state,'current_report_period':cur['report_period'] if cur else (latest_period or ''),'current_publication_date':cur.get('publication_date','') if cur else '','current_available_date':cur.get('available_date','') if cur else '','current_holding_ratio':cur.get('holding_ratio','') if cur else '','previous_report_period':prev['report_period'] if prev else '','previous_holding_ratio':prev.get('holding_ratio','') if prev else '','evidence_grade':base.get('source_grade','') if base else 'UNKNOWN'})
 e=list(csv.DictReader((OUT/'etf_share_daily_sse.csv').open()));market=[]
 for code in sorted({r['etf_code'] for r in e}):
  rs=sorted([r for r in e if r['etf_code']==code and r.get('availability_status')=='AVAILABLE_PIT' and r.get('available_date')<=T],key=lambda x:x['trade_date'])
  if not rs:continue
  latest_e=rs[-1];prev=rs[-2] if len(rs)>1 else None;v=num(latest_e.get('total_shares'));p=num(prev.get('total_shares')) if prev else None;state='STABLE' if prev is None or v==p else 'EXPANSION' if v>p else 'CONTRACTION';market.append({'context_record_id':f'E-{len(market):06d}','capital_layer':'MARKET','evidence_type':'ETF_TOTAL_SHARES','etf_code_hash':hashlib.sha256(code.encode()).hexdigest(),'latest_trade_date':latest_e['trade_date'],'latest_available_date':latest_e['available_date'],'latest_total_shares':latest_e['total_shares'],'previous_trade_date':prev['trade_date'] if prev else '','previous_total_shares':prev['total_shares'] if prev else '','share_change':str(v-p) if prev and v is not None and p is not None else '','share_change_ratio':str((v-p)/p) if prev and v is not None and p else '','state':state,'actor_attribution':'FORBIDDEN'})
 ctx={'context_version':'csr8-national-capital-v1','evidence_profile':'BASE_V1+NATIONAL_CTX_V1','ordinal':a.ordinal,'packet_id':packet,'as_of':{'T':T,'availability_rule':'available_date<=T'},'stock_capital_records':stock,'market_etf_records':market,'limitations':[{'status':'UNAVAILABLE','scope':'SZSE_ETF_HISTORY'}],'source_commitments':{'holdings_sha256':hashlib.sha256((OUT/'national_holdings_pit.csv').read_bytes()).hexdigest(),'etf_sha256':hashlib.sha256((OUT/'etf_share_daily_sse.csv').read_bytes()).hexdigest()},'context_commitment_sha256':''};ctx['context_commitment_sha256']=hashlib.sha256(canon({k:v for k,v in ctx.items() if k!='context_commitment_sha256'}).encode()).hexdigest();Path(a.out).write_text(json.dumps(ctx,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'out':a.out,'packet_id':packet,'records':len(stock)+len(market),'context_commitment_sha256':ctx['context_commitment_sha256']},ensure_ascii=False))
if __name__=='__main__':main()
