#!/usr/bin/env python3
"""NC final prerequisite audit; never declares independent approval or appends H events."""
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'docs/audit/evidence';DATA=ROOT/'output/research/csr/national_capital'
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 checks={'actor_registry_deterministic':json.loads((DATA/'actor_registry_audit.json').read_text())['status']=='PASS','raw_provenance_exact':json.loads((DATA/'holdings_coverage_ledger_report.json').read_text())['status']=='PASS','publication_provenance_pass':json.loads((DATA/'publication_provenance_audit.json').read_text())['status']=='PASS','strict_available_date':all(x['available_date']>x['publication_date'] for x in __import__('csv').DictReader((DATA/'national_holdings_pit.csv').open())),'empty_unavailable':json.loads((DATA/'empty_resolution_report.json').read_text())['not_disclosed_cells']==0,'etf_attribution_forbidden':all(r.get('actor_attribution')=='FORBIDDEN' for r in json.loads(Path('/tmp/nc4-context.json').read_text()).get('market_etf_records',[])),'nc0_invariance':json.loads((OUT/'national_capital_production_invariance.json').read_text())['passed'],'context_preflight':json.loads((OUT/'national_capital_context_preflight.json').read_text()).get('status')=='PASS','support_contract':json.loads((OUT/'support_contract_test_report.json').read_text()).get('status')=='PASS'}
 files=['config/csr/national_actor_registry_v1.json','output/research/csr/national_capital/holdings_coverage_ledger.csv','output/research/csr/national_capital/national_holdings_pit.csv','output/research/csr/national_capital/publication_provenance_audit.json','output/research/csr/national_capital/empty_resolution_report.json','output/research/csr/national_capital/etf_share_daily_sse.csv','output/research/csr/national_capital/etf_lineage_report.json','docs/audit/evidence/national_capital_extension_pause_anchor.json','docs/audit/evidence/national_capital_production_invariance.json']; report={'checks':checks,'passed':all(checks.values()),'state':'PREREQUISITES_COMPLETE' if all(checks.values()) else 'INCOMPLETE','independent_approval':'NOT_DECLARED','artifact_sha256':{x:h(ROOT/x) for x in files if (ROOT/x).exists()},'no_r4_s4':len([x for x in (ROOT/'data/csr8_phase_c/production/c4-prod-0002/sealing/sealing_log.jsonl').read_text().splitlines() if x.strip()])==6};(OUT/'national_capital_context_extension_final_audit.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
