#!/usr/bin/env python3
"""Machine production gates for the NC sidecar."""
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'output/research/csr/national_capital'
def main():
 h=list(csv.DictReader((OUT/'national_holdings_pit.csv').open()));e=list(csv.DictReader((OUT/'etf_share_daily_sse.csv').open()));ledger=json.loads((OUT/'holdings_coverage_ledger_report.json').read_text());lineage=json.loads((OUT/'etf_lineage_report.json').read_text());inv=json.loads((ROOT/'docs/audit/evidence/national_capital_production_invariance.json').read_text());anchor=ROOT/'docs/audit/evidence/national_capital_extension_pause_anchor.json'
 checks={'holdings_matrix_84x22':ledger.get('status')=='PASS' and ledger.get('expected_cells')==1848 and ledger.get('ledger_cells')==1848,'holdings_pit_fields':all(x.get('publication_date') not in ('','UNKNOWN') and x.get('available_date') not in ('','UNKNOWN') and x.get('available_date')>x.get('publication_date') for x in h),'holdings_raw_sha':all(x.get('raw_sha256') for x in h),'holdings_source_empty_explicit':ledger.get('empty_unknown')==50,'etf_lineage':lineage.get('status')=='PASS' and all(x.get('raw_sha_verified') and (x.get('availability_status')=='AVAILABLE_PIT' or not x.get('available_date')) for x in e),'nc0_pause_anchor':anchor.exists(),'frozen_chain_untouched':inv.get('passed') is True}
 report={'generated_at':'2026-10-02','checks':checks,'passed':all(checks.values()),'production_status':'READY_AS_SIDECAR_INPUTS' if all(checks.values()) else 'NOT_READY','nonblocking_limitations':{'empty_holdings':{'status':'UNAVAILABLE','absence_semantics':'UNKNOWN','nonblocking':True},'publication_source':{'status':'SECONDARY_CAPTURED','official_cross_check':'OPTIONAL_ENRICHMENT'},'residual_actor_names':{'status':'UNMATCHED','excluded_from_actor_evidence':True,'llm_role':'proposal_only'},'szse_etf_history':{'status':'OPTIONAL_ENRICHMENT','availability':'UNAVAILABLE','nonblocking':True}}};(OUT/'production_readiness_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps(report,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
